name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t 23mahesh/docker-full-stack-server:latest ./server
          docker push 23mahesh/docker-full-stack-server:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t 23mahesh/docker-full-stack-client:latest ./client
          docker push 23mahesh/docker-full-stack-client:latest
