name: Compose Up

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed

jobs:
  compose-up:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2
        with:
          compose-file: docker-compose.yml

      - name: Run docker-compose up
        run: docker-compose up -d
